[package]
name = "just_enough_mod_core"
description = "The core libary for JustEnoughMod"
version = "0.0.1"
authors = ["LDprg <lukas_4dr@gmx.at>"]
edition = "2021"
license = "MIT"

[dependencies]
bevy = { version = "0.12", features = [ "wayland", "dynamic_linking" ] }