var annotated_dup =
[
    [ "docstring", "namespacedocstring.html", [
      [ "PyClass", "classdocstring_1_1PyClass.html", "classdocstring_1_1PyClass" ]
    ] ],
    [ "JEM", null, [
      [ "Application", "classJEM_1_1Application.html", null ],
      [ "AppModule", "classJEM_1_1AppModule.html", null ],
      [ "EventManager", "classJEM_1_1EventManager.html", null ],
      [ "ExitEvent", "structJEM_1_1ExitEvent.html", null ],
      [ "InstanceExtensions", "structJEM_1_1InstanceExtensions.html", null ],
      [ "KeyPressedEvent", "structJEM_1_1KeyPressedEvent.html", null ],
      [ "KeyReleasedEvent", "structJEM_1_1KeyReleasedEvent.html", null ],
      [ "Logger", "classJEM_1_1Logger.html", null ],
      [ "MouseButtonPressedEvent", "structJEM_1_1MouseButtonPressedEvent.html", null ],
      [ "MouseButtonReleasedEvent", "structJEM_1_1MouseButtonReleasedEvent.html", null ],
      [ "MouseMoveEvent", "structJEM_1_1MouseMoveEvent.html", null ],
      [ "MouseWheelEvent", "structJEM_1_1MouseWheelEvent.html", null ],
      [ "Plugin", "classJEM_1_1Plugin.html", null ],
      [ "PluginLoader", "classJEM_1_1PluginLoader.html", null ],
      [ "queue", "classJEM_1_1queue.html", null ],
      [ "Renderer", "classJEM_1_1Renderer.html", null ],
      [ "Task", "classJEM_1_1Task.html", null ],
      [ "TaskManager", "classJEM_1_1TaskManager.html", null ],
      [ "TaskPool", "classJEM_1_1TaskPool.html", null ],
      [ "TextInputEvent", "structJEM_1_1TextInputEvent.html", null ],
      [ "Version", "classJEM_1_1Version.html", null ],
      [ "Window", "classJEM_1_1Window.html", null ]
    ] ],
    [ "pyexample", "namespacepyexample.html", [
      [ "PyClass", "classpyexample_1_1PyClass.html", "classpyexample_1_1PyClass" ]
    ] ],
    [ "A", "classA.html", null ],
    [ "Afterdoc_Test", "classAfterdoc__Test.html", "classAfterdoc__Test" ],
    [ "Autolink_Test", "classAutolink__Test.html", "classAutolink__Test" ],
    [ "B", "classB.html", null ],
    [ "C", "classC.html", null ],
    [ "C1", "classC1.html", null ],
    [ "C2", "classC2.html", null ],
    [ "C3", "classC3.html", null ],
    [ "C4", "classC4.html", null ],
    [ "C5", "classC5.html", null ],
    [ "Car", "structCar.html", "structCar" ],
    [ "CoordStruct", "structCoordStruct.html", "structCoordStruct" ],
    [ "D", "classD.html", null ],
    [ "E", "classE.html", null ],
    [ "Enum_Test", "classEnum__Test.html", "classEnum__Test" ],
    [ "Example_Test", "classExample__Test.html", "classExample__Test" ],
    [ "Fn_Test", "classFn__Test.html", "classFn__Test" ],
    [ "Include_Test", "classInclude__Test.html", "classInclude__Test" ],
    [ "Javadoc_Test", "classJavadoc__Test.html", "classJavadoc__Test" ],
    [ "Memgrp_Test", "classMemgrp__Test.html", "classMemgrp__Test" ],
    [ "mux_using_with", "classmux__using__with.html", "classmux__using__with" ],
    [ "Object", "structObject.html", null ],
    [ "Overload_Test", "classOverload__Test.html", "classOverload__Test" ],
    [ "Par_Test", "classPar__Test.html", null ],
    [ "QTstyle_Test", "classQTstyle__Test.html", "classQTstyle__Test" ],
    [ "SomeNiceClass", "classSomeNiceClass.html", null ],
    [ "String", "classString.html", "classString" ],
    [ "Tag", "classTag.html", "classTag" ],
    [ "Test", "classTest.html", "classTest" ],
    [ "Test< T * >", "classTest_3_01T_01_5_01_4.html", "classTest_3_01T_01_5_01_4" ],
    [ "Test< void *, 200 >", "classTest_3_01void_01_5_00_01200_01_4.html", "classTest_3_01void_01_5_00_01200_01_4" ],
    [ "Truck", "structTruck.html", "structTruck" ],
    [ "Vehicle", "structVehicle.html", "structVehicle" ]
];