[package]
name = "JustEnoughMod"
version = "0.1.0"
edition = "2021"
license = "MIT"

[profile.dev]
opt-level = 1

[profile.dev.pacakge."*"]
opt-level = 3

[dependencies]
bevy = { version = "0.12", features = [ "wayland" ] }