[package]
name = "JustEnoughMod_base"
description = "The base plugin for JustEnoughMod"
version = "0.0.1"
authors = ["LDprg <lukas_4dr@gmx.at>"]
edition = "2021"
license = "MIT"


[lib]
crate-type = ["dylib"]

[dependencies]
JustEnoughMod_core = { path = "../JustEnoughMod_core" }