jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install LLVM and Clang
      uses: KyleMayes/install-llvm-action@v1.9.0
      with:
        version: "17.0"
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install Python Dependencies
      run: pip install meson ninja
    - name: Install Project Dependencies
      run: sudo apt-get install -y libglfw3-dev libwayland-dev libvulkan-dev
    - name: Prepare Build
      run: meson setup build
      env:
        CC: clang
        CXX: clang++
    - name: Run Build
      run: meson compile -v -C build
      env:
        CC: clang
        CXX: clang++
    - name: Run Test Suite
      run: meson test -v -C build
      env:
        CC: clang
        CXX: clang++

on:
  pull_request:
  push:
