jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up GCC
      uses: egor-tensin/setup-gcc@v1
      with:
        version: 14
        platform: x64
        cc: 1
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install Python Dependencies
      run: pip install meson ninja
    - name: Install Project Dependencies
      run: sudo apt-get install -y libglfw3-dev libwayland-dev libvulkan-dev
    - name: Prepare Build
      run: meson setup build
    - name: Run Build
      run: meson compile -v -C build
    - name: Run Test Suite
      run: meson test -v -C build

on:
  pull_request:
  push:
