on:
  pull_request:
  push:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install Python Dependencies
      run: pip install meson ninja
    - name: Install Mesa & SDL2
      run: sudo apt-get install -y libsdl2-dev mesa-utils mesa-common-dev libwayland-dev
    - name: Prepare Build
      run: meson setup build
    - name: Run Build
      run: meson compile -v -C build
    - name: Run Test Suite
      run: meson test -v -C build
