jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: JustEnoughMod/doxygen-github-pages-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: build_docs/html
          config_file: Doxyfile

name: Doxygen GitHub Pages Deploy Action

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
    contents: write
