on:
  pull_request:
  push:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup C++
      uses: alandefreitas/cpp-actions/setup-cpp@master
      id: setup-cpp
      with:
        compiler: clang
        version: 16
    - uses: pre-commit/action@v3.0.1
    - uses: pre-commit-ci/lite-action@v1.0.2
      if: always()
