jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install LLVM and Clang
      uses: KyleMayes/install-llvm-action@v1.9.0
      with:
        version: "16.0"
    - uses: pre-commit/action@v3.0.1
    - uses: pre-commit-ci/lite-action@v1.0.2
      if: always()

on:
  pull_request:
  push:
